name: PROD Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies & Build Client
        run: |
           rm -rf node_modules package-lock.json
           npm cache clean --force
           cd client
           npm install esbuild embla-carousel-react recharts cmdk vaul input-otp react-resizable-panels drizzle-orm drizzle-zod zod
           cd ..
           cd server
           npm install drizzle-orm drizzle-zod zod
           cd ..
           cd client && npm install && npm run build && cd .. && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
           cd ..
           mkdir -p dist
      - name: Ensure destination directory exists
        run: mkdir -p dist
      - name: Copy Build Files
        run: cp -r client/dist/* dist/
        
      - name: Deploy to Vercel
        run: |
          npm install --global vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
